import { StyleSheet } from 'react-native-unistyles';

export const styles = StyleSheet.create((theme, rt) => ({
  mainContainer: {
    flex: 1,
    paddingTop: rt.insets.top,
  },
  container: {
    paddingTop: 20,
    width: '100%',
    paddingHorizontal: 20,
    gap: 20,
    // justifyContent: 'center',
    // alignItems: 'center',
    height: '100%',
  },
  input: {
    height: 40,
    width: 350,
    borderWidth: 1,
    borderTopLeftRadius: 25,
    borderBottomLeftRadius: 25,
    borderTopRightRadius: 25,
    borderBottomRightRadius: 8,
    borderColor: theme.colors.neutral5,
    paddingHorizontal: 16,
    color: theme.colors.text,
  },
  inputError: {
    borderColor: theme.colors.red,
  },
  profileInputError: {
    borderWidth: 1,
    borderColor: theme.colors.red,
  },
  submit: {
    height: 60,
    width: 60,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 9999,
    backgroundColor: theme.colors.icon,
  },
  submitText: {
    color: theme.colors.background,
    fontWeight: 'bold',
    fontSize: 16,
  },
  bio: {
    height: 100,
    width: 350,
    borderWidth: 1,
    borderTopLeftRadius: 25,
    borderBottomLeftRadius: 25,
    borderTopRightRadius: 25,
    borderBottomRightRadius: 8,
    borderColor: theme.colors.neutral5,
    paddingHorizontal: 16,
    paddingVertical: 10,
    color: theme.colors.text,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    width: 350,
    height: 40,
    borderWidth: 1,
    borderTopLeftRadius: 25,
    borderBottomLeftRadius: 25,
    borderTopRightRadius: 25,
    borderBottomRightRadius: 8,
    borderColor: theme.colors.neutral5,
    paddingRight: 16,
  },
  inputField: {
    flex: 1,
    width: '100%',
    height: '100%',
    color: theme.colors.text,
    paddingHorizontal: 16,
  },
  inputButton: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  profileVisibleToContainer: {
    width: 350,
    height: 40,
    borderColor: theme.colors.neutral5,
    borderWidth: 1,
    borderTopLeftRadius: 25,
    borderBottomLeftRadius: 25,
    borderTopRightRadius: 25,
    borderBottomRightRadius: 8,
  },
  profilePictureContainer: {
    // height: 240,
    // width: Platform.OS === 'web' ? '20%' : 80,
    // backgroundColor: theme.colors.yellow,
    // gap: 5

    paddingBottom: 20,
  },
  profilePicture: {
    height: 80,
    width: 80,
    backgroundColor: theme.colors.icon,
    borderRadius: 9999,
  },
  profilePictureImage: {
    width: '100%',
    height: '100%',
    pointerEvents: 'none',
    borderRadius: 9999,
  },
  outerEditIcon: {
    // marginTop: 10,
    // backgroundColor: theme.colors.yellow,
    // marginBottom: 20,
    // paddingLeft: 25,
  },
  editIcon: {
    // width: 125,
    // backgroundColor: theme.colors.background,
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
  },
  bucketText: {
    color: theme.colors.text,
    fontSize: 13,
    // fontWeight: 'bold',
  },
  dropdownBorder: {
    height: 38,
    width: 340,
    borderWidth: 0,
    borderTopLeftRadius: 25,
    borderBottomLeftRadius: 25,
    borderBottomRightRadius: 8,
    borderTopRightRadius: 25,
    paddingHorizontal: 16,
  },
}));

export type UpdateProfileStyles = typeof styles;
